#!/usr/bin/env python3
"""Compile the Vulkan XR composite shaders into an embedded SPIR-V table.

app/src/main/cpp/xrimmersive/shaders/*.{vert,frag} -> xrimmersive/xr_vulkan_shaders.inc. The
generated file is committed so APK builds need no shader compiler; rerun this after editing a
shader. Requires glslangValidator (the WSL build host has 15.1.0 at /usr/local/bin).
"""
import argparse
import hashlib
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SHADERS = ROOT / "app/src/main/cpp/xrimmersive/shaders"
OUTPUT = ROOT / "app/src/main/cpp/xrimmersive/xr_vulkan_shaders.inc"


def symbol(path: Path) -> str:
    stem = "".join(part.capitalize() for part in path.stem.split("_"))
    return f"k{stem}{path.suffix[1:].capitalize()}"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--glslang", default=shutil.which("glslangValidator"))
    parser.add_argument("--check", action="store_true", help="fail if the committed table differs")
    args = parser.parse_args()
    if not args.glslang:
        parser.error("glslangValidator not found; pass --glslang")
    version = subprocess.run([args.glslang, "--version"], capture_output=True, text=True).stdout.splitlines()[0]
    sources = sorted(list(SHADERS.glob("*.vert")) + list(SHADERS.glob("*.frag")))
    lines = [
        "// Generated by tools/xrgame/compile-xr-shaders.py from xrimmersive/shaders; do not edit.",
        f"// {version}",
    ]
    with tempfile.TemporaryDirectory() as work:
        for source in sources:
            spv = Path(work) / (source.name + ".spv")
            subprocess.run([args.glslang, "-V", "--target-env", "vulkan1.1", "-o", str(spv), str(source)],
                           check=True, capture_output=True)
            data = spv.read_bytes()
            words = [int.from_bytes(data[i:i + 4], "little") for i in range(0, len(data), 4)]
            digest = hashlib.sha256(source.read_bytes()).hexdigest()[:16]
            lines.append(f"// {source.name} sha256 {digest}")
            lines.append(f"static const uint32_t {symbol(source)}[] = {{")
            for i in range(0, len(words), 8):
                lines.append("    " + ", ".join(f"0x{w:08x}" for w in words[i:i + 8]) + ",")
            lines.append("};")
    text = "\n".join(lines) + "\n"
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text() != text:
            print(f"{OUTPUT} is stale", file=sys.stderr)
            return 1
        return 0
    OUTPUT.write_text(text, newline="\n")
    print(f"wrote {OUTPUT} ({len(sources)} shaders)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
